/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        display: ["Bricolage Grotesque Variable", "Inter", "system-ui", "sans-serif"],
        accent: ["Instrument Serif", "Georgia", "serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "monospace"],
        ui: ["Inter", "system-ui", "sans-serif"],
        serif: ["var(--font-serif)", "Cormorant Garamond", "Georgia", "serif"],
        sans: ["var(--font-sans)", "Inter", "-apple-system", "sans-serif"],
      },
      colors: {
        paper: { DEFAULT: "#F2EDE3", 2: "#E9E2D4" },
        ink: { DEFAULT: "#151412", soft: "#57524B" },
        signal: "#FF5B2E",
        night: { DEFAULT: "#0F1627", ink: "#E8E6DF", soft: "#9AA3B5", moon: "#EFE6D0" },
        botanical: { DEFAULT: "#DFE6CF", ink: "#213520", leaf: "#4F6B45" },
        romantic: { DEFAULT: "#ECD3CD", wine: "#5A1E2B" },
        film: { DEFAULT: "#F1D9A5", amber: "#D8913B" },
        "bg-primary": "#FAF7F2",
        "bg-secondary": "#F4EFEB",
        "bg-card": "#FFFFFF",
        "bg-card-hover": "#FDFBF7",
        "accent-gold": "#B76E79",
        "accent-gold-hover": "#A05C66",
        "accent-rosegold": "#B76E79",
        "accent-rosegold-hover": "#A05C66",
        cream: {
          50: "#FDFBF7",
          100: "#FAF7F2",
          200: "#F4EFEB",
          300: "#EAE3DC",
        },
        blush: {
          50: "#FDF6F5",
          100: "#F7E8E5",
          200: "#E8C5B8",
          300: "#D9A596",
          500: "#B76E79",
          600: "#9E5560",
        },
        sage: {
          50: "#F4F7F4",
          100: "#E3EAE2",
          200: "#C4D4C3",
          400: "#8A9A86",
          500: "#738671",
          600: "#63745F",
        },
        sand: {
          50: "#FAF7F2",
          100: "#F0EAE1",
          200: "#D8C7B5",
          400: "#A68B6D",
          500: "#A67C52",
          600: "#7A6347",
        },
        charcoal: {
          700: "#4A453F",
          800: "#3D3A36",
          900: "#2D2A26",
        },
      },
    },
  },
  plugins: [],
};
